# .github/workflows/ci.yml

name: Flask App CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install dependencies from requirements.txt if it exists
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirement.txt ]; then pip install -r requirement.txt; fi

      # Set up the virtual environment and navigate to the app directory
      - name: Set up Virtual Environment and Navigate
        run: |
          python -m venv venv
          source venv/bin/activate

      # Run Health Check Unit Tests from `app/test`
      - name: Run Health Check Tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s test -p "test_healthcheck.py" | tee healthcheck_output.log

      # Run User API Unit Tests from `app/test`
      - name: Run User API Tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s test -p "test_user.py" | tee user_test_output.log

      # Search for "error" in Healthz API test output log and fail if found
      - name: Check Health Check Test Output for Errors
        run: |
          python -m unittest discover -s app/tests -p "test_healthcheck.py" | tee test_output.log
          echo "HERE"
          cat test_output.log
          if grep -E "FAIL|ERROR|Traceback" test_output.log; then
            echo "Test failed due to an error or failure!"
            exit 1
          fi

      # Search for "error" in user API test output log and fail if found
      - name: Check User API Test Output for Errors
        run: |
          python -m unittest discover -s app/tests -p "test_user.py" | tee test_output.log
          if grep -E "FAIL|ERROR|Traceback" test_output.log; then
            echo "Test failed due to an error or failure!"
            exit 1
          fi
