# .github/workflows/ci.yml

name: Flask App CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install dependencies from requirements.txt if it exists
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirement.txt ]; then pip install -r requirement.txt; fi

      # Set up the virtual environment and navigate to the app directory
      - name: Set up Virtual Environment and Navigate
        run: |
          python -m venv venv
          source venv/bin/activate
          cd app

      # Run Health Check Unit Tests from `app/test`
      - name: Run Health Check Tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s test -p "test_health_check.py" | tee health_check_output.log

      # Run User API Unit Tests from `app/test`
      - name: Run User API Tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s test -p "test_user.py" | tee user_test_output.log

      # Search for "error" in health check output log and fail if found
      - name: Check Health Check Test Output for Errors
        run: |
          if grep -i "error" health_check_output.log; then
            echo "Error found in Health Check Test output!"
            exit 1
          else
            echo "No errors found in Health Check Test output."
          fi

      # Search for "error" in user API test output log and fail if found
      - name: Check User API Test Output for Errors
        run: |
          if grep -i "error" user_test_output.log; then
            echo "Error found in User API Test output!"
            exit 1
          else
            echo "No errors found in User API Test output."
          fi
