name: Packer Validate & Format

on:
  pull_request:
    branches:
      - main

jobs:
  validate-packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Package application
        run: |
          cp -r app webapp/
          cp run.py webapp/
          cp requirement.txt webapp/
          cp README.md webapp/
          zip -r webapp.zip webapp/

      - name: Packer Build
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: "Initialize Packer"
        run: |
          cd packer
          packer init .

      - name: Check Packer formatting
        run: |
          echo "Checking Packer template formatting..."
          packer fmt -check packer/.
          if [ $? -ne 0 ]; then
            echo "Packer format check failed. Fix the formatting and try again."
            exit 1
          fi

      - name: Validate Packer template
        run: |
          echo "Validating Packer template..."
          cd packer
          packer validate packer/.
          if [ $? -ne 0 ]; then
            echo "Packer format check failed. Fix the formatting and try again."
            exit 1
          fi

      - name: Check Shell scripts
        run: |
          echo "Checking shell script formatting and syntax..."
          find . -name "*.sh" -exec shellcheck {} \;
          if [ $? -ne 0 ]; then
            echo "Shell script check failed. Fix the issues and try again."
            exit 1
          fi
